name: Build and Test
on: [ push, pull_request ]

jobs:
  check:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Copy config file
        run: cp example.config.ts config.ts
        
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Remove fake config.js
        run: rm build/config.js

      - name: Deploy with gh-pages
        if: ${{ github.ref_name == 'stable' }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -b "build" -m "build: Hosting build for branch ${GITHUB_REF##*/} - ${GITHUB_SHA::7}" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}